<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Form_jenis extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        is_login();
        $this->load->model('Form_jenis_model');
        $this->load->library('form_validation');
    }

    public function index()
    {
        $q = urldecode($this->input->get('q', TRUE));
        $start = intval($this->uri->segment(3));
        
        if ($q <> '') {
            $config['base_url'] = base_url() . '.php/c_url/index.html?q=' . urlencode($q);
            $config['first_url'] = base_url() . 'index.php/form_jenis/index.html?q=' . urlencode($q);
        } else {
            $config['base_url'] = base_url() . 'index.php/form_jenis/index/';
            $config['first_url'] = base_url() . 'index.php/form_jenis/index/';
        }

        $config['per_page'] = 10;
        $config['page_query_string'] = FALSE;
        $config['total_rows'] = $this->Form_jenis_model->total_rows($q);
        $form_jenis = $this->Form_jenis_model->get_limit_data($config['per_page'], $start, $q);
        $config['full_tag_open'] = '<ul class="pagination pagination-sm no-margin pull-right">';
        $config['full_tag_close'] = '</ul>';
        $this->load->library('pagination');
        $this->pagination->initialize($config);

        $data = array(
            'form_jenis_data' => $form_jenis,
            'q' => $q,
            'pagination' => $this->pagination->create_links(),
            'total_rows' => $config['total_rows'],
            'start' => $start,
        );
        $this->template->load('template','form_jenis/form_jenis_list', $data);
    }

    public function read($id) 
    {
        $row = $this->Form_jenis_model->get_by_id($id);
        if ($row) {
            $data = array(
		'form_id' => $row->form_id,
		'nama_form' => $row->nama_form,
	    );
            $this->template->load('template','form_jenis/form_jenis_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('form_jenis'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('form_jenis/create_action'),
	    'form_id' => set_value('form_id'),
	    'nama_form' => set_value('nama_form'),
	);
        $this->template->load('template','form_jenis/form_jenis_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'nama_form' => $this->input->post('nama_form',TRUE),
	    );

            $this->Form_jenis_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success 2');
            redirect(site_url('form_jenis'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Form_jenis_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('form_jenis/update_action'),
		'form_id' => set_value('form_id', $row->form_id),
		'nama_form' => set_value('nama_form', $row->nama_form),
	    );
            $this->template->load('template','form_jenis/form_jenis_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('form_jenis'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('form_id', TRUE));
        } else {
            $data = array(
		'nama_form' => $this->input->post('nama_form',TRUE),
	    );

            $this->Form_jenis_model->update($this->input->post('form_id', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('form_jenis'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Form_jenis_model->get_by_id($id);

        if ($row) {
            $this->Form_jenis_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('form_jenis'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('form_jenis'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('nama_form', 'nama form', 'trim|required');

	$this->form_validation->set_rules('form_id', 'form_id', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Form_jenis.php */
/* Location: ./application/controllers/Form_jenis.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-03-01 08:59:19 */
/* http://harviacode.com */