<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Password extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        is_login();
        $this->load->model('Password_model');
        $this->load->library('form_validation');
    }

    public function index()
    {
        $q = urldecode($this->input->get('q', TRUE));
        $start = intval($this->uri->segment(3));
        
        if ($q <> '') {
            $config['base_url'] = base_url() . '.php/c_url/index.html?q=' . urlencode($q);
            $config['first_url'] = base_url() . 'index.php/password/index.html?q=' . urlencode($q);
        } else {
            $config['base_url'] = base_url() . 'index.php/password/index/';
            $config['first_url'] = base_url() . 'index.php/password/index/';
        }

        $config['per_page'] = 10;
        $config['page_query_string'] = FALSE;
        $config['total_rows'] = $this->Password_model->total_rows($q);
        $password = $this->Password_model->get_limit_data($config['per_page'], $start, $q);
        $config['full_tag_open'] = '<ul class="pagination pagination-sm no-margin pull-right">';
        $config['full_tag_close'] = '</ul>';
        $this->load->library('pagination');
        $this->pagination->initialize($config);

        $data = array(
            'password_data' => $password,
            'q' => $q,
            'pagination' => $this->pagination->create_links(),
            'total_rows' => $config['total_rows'],
            'start' => $start,
        );
        $this->template->load('template','password/password_list', $data);
    }

    public function read($id) 
    {
        $row = $this->Password_model->get_by_id($id);
        if ($row) {
            $data = array(
		'type' => $row->type,
		'password' => $row->password,
	    );
            $this->template->load('template','password/password_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('password'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('password/create_action'),
	    'type' => set_value('type'),
	    'password' => set_value('password'),
	);
        $this->template->load('template','password/password_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'type' => $this->input->post('type',TRUE),
		'password' => $this->input->post('password',TRUE),
	    );

            $this->Password_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success 2');
            redirect(site_url('password'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Password_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('password/update_action'),
		'type' => set_value('type', $row->type),
		'password' => set_value('password', $row->password),
	    );
            $this->template->load('template','password/password_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('password'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('', TRUE));
        } else {
            $data = array(
		'type' => $this->input->post('type',TRUE),
		'password' => $this->input->post('password',TRUE),
	    );

            $this->Password_model->update($this->input->post('', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('password'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Password_model->get_by_id($id);

        if ($row) {
            $this->Password_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('password'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('password'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('type', 'type', 'trim|required');
	$this->form_validation->set_rules('password', 'password', 'trim|required');

	$this->form_validation->set_rules('', '', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Password.php */
/* Location: ./application/controllers/Password.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-03-01 08:59:51 */
/* http://harviacode.com */