<?php
date_default_timezone_set('Asia/Jakarta');
if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Product_category extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        is_login();
        $this->load->model('Product_category_model');
        $this->load->library('form_validation');        
	$this->load->library('datatables');
    }

    public function index()
    {
        $this->template->load('template','product_category/product_category_list');
    } 
    
    public function json() {
        header('Content-Type: application/json');
        echo $this->Product_category_model->json();
    }

    public function read($id) 
    {
        $row = $this->Product_category_model->get_by_id($id);
        if ($row) {
            $data = array(
		'category_id' => $row->category_id,
		'category_name' => $row->category_name,
	    );
            $this->template->load('template','product_category/product_category_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('product_category'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('product_category/create_action'),
	    'category_id' => set_value('category_id'),
	    'category_name' => set_value('category_name'),
	);
        $this->template->load('template','product_category/product_category_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'category_name' => $this->input->post('category_name',TRUE),
	    );

            $this->Product_category_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success 2');
            redirect(site_url('product_category'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Product_category_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('product_category/update_action'),
		'category_id' => set_value('category_id', $row->category_id),
		'category_name' => set_value('category_name', $row->category_name),
	    );
            $this->template->load('template','product_category/product_category_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('product_category'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('category_id', TRUE));
        } else {
            $data = array(
		'category_name' => $this->input->post('category_name',TRUE),
	    );

            $this->Product_category_model->update($this->input->post('category_id', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('product_category'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Product_category_model->get_by_id($id);

        if ($row) {
            $this->Product_category_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('product_category'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('product_category'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('category_name', 'category name', 'trim|required');

	$this->form_validation->set_rules('category_id', 'category_id', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Product_category.php */
/* Location: ./application/controllers/Product_category.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-08-18 04:56:34 */
/* http://harviacode.com */