<?php
date_default_timezone_set('Asia/Jakarta');
if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Promotion_financial_desc extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        is_login();
        $this->load->model('Promotion_financial_desc_model');
        $this->load->library('form_validation');        
	$this->load->library('datatables');
    }

    public function index()
    {
        $this->template->load('template','promotion_financial_desc/promotion_financial_desc_list');
    } 
    
    public function json() {
        header('Content-Type: application/json');
        echo $this->Promotion_financial_desc_model->json();
    }

    public function read($id) 
    {
        $row = $this->Promotion_financial_desc_model->get_by_id($id);
        if ($row) {
            $data = array(
		'financial_desc_id' => $row->financial_desc_id,
		'financial_name' => $row->financial_name,
	    );
            $this->template->load('template','promotion_financial_desc/promotion_financial_desc_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('promotion_financial_desc'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('promotion_financial_desc/create_action'),
	    'financial_desc_id' => set_value('financial_desc_id'),
	    'financial_name' => set_value('financial_name'),
	);
        $this->template->load('template','promotion_financial_desc/promotion_financial_desc_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'financial_name' => $this->input->post('financial_name',TRUE),
	    );

            $this->Promotion_financial_desc_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success 2');
            redirect(site_url('promotion_financial_desc'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Promotion_financial_desc_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('promotion_financial_desc/update_action'),
		'financial_desc_id' => set_value('financial_desc_id', $row->financial_desc_id),
		'financial_name' => set_value('financial_name', $row->financial_name),
	    );
            $this->template->load('template','promotion_financial_desc/promotion_financial_desc_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('promotion_financial_desc'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('financial_desc_id', TRUE));
        } else {
            $data = array(
		'financial_name' => $this->input->post('financial_name',TRUE),
	    );

            $this->Promotion_financial_desc_model->update($this->input->post('financial_desc_id', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('promotion_financial_desc'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Promotion_financial_desc_model->get_by_id($id);

        if ($row) {
            $this->Promotion_financial_desc_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('promotion_financial_desc'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('promotion_financial_desc'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('financial_name', 'financial name', 'trim|required');

	$this->form_validation->set_rules('financial_desc_id', 'financial_desc_id', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Promotion_financial_desc.php */
/* Location: ./application/controllers/Promotion_financial_desc.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-08-17 15:02:32 */
/* http://harviacode.com */