<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Arc_departemen_model extends CI_Model
{

    public $table = 'arc_departemen';
    public $id = 'dept_id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('dept_id,kode_departemen,nama_departemen');
        $this->datatables->from('arc_departemen');
        //add this line for join
        //$this->datatables->join('table2', 'arc_departemen.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('arc_departemen/update/$1'),'<i class="fa fa-pencil-square-o" aria-hidden="true"></i>', array('class' => 'btn btn-warning btn-sm'))." 
                ".anchor(site_url('arc_departemen/delete/$1'),'<i class="fa fa-trash-o" aria-hidden="true"></i>','class="btn btn-danger btn-sm" onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'dept_id');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('dept_id', $q);
	$this->db->or_like('kode_departemen', $q);
	$this->db->or_like('nama_departemen', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('dept_id', $q);
	$this->db->or_like('kode_departemen', $q);
	$this->db->or_like('nama_departemen', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Arc_departemen_model.php */
/* Location: ./application/models/Arc_departemen_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-01-20 05:38:53 */
/* http://harviacode.com */